---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project }}-{{ role }}
  labels:
    app: {{ project }}-{{ role }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ project }}-{{ role }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ project }}-{{ role }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9000"
    spec:
      containers:
        - env:
          - name: SERVER_HOST
            value: http://172.26.197.20:8088
          - name: UI_HOST
            value: http://172.26.197.20:30030
          - name: UI_FILE_HOST
            value: http://172.26.197.20:30030
          - name: SERVER_PORT
            value: '80'
          name: {{ project }}-{{ role }}
          image: {{ image_name }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 1000Mi
              cpu: 1000m
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 1
      imagePullSecrets:
        - name: default-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ project }}
  name: {{ project }}
spec:
  type: NodePort
  selector:
    app: {{ project }}-{{ role }}
  ports:
      - name: "80"
        port: 80
        protocol: TCP
        targetPort: 80
        nodePort: 30066
